### ISSUE TITLE
"Абу Абдуллах Мухаммед ибн Муса аль-Хорезми"

### ISSUE THREAD

**Issue by bzaar** [UniversalDependencies/UD_Russian-SynTagRus#21]
На ruscorpora вершиной [является](http://ruscorpora.ru/syntax/2013/algoritm_35.pdf) Абдуллах, а у вас - Абу. Разве это не один и тот же СинТагРус?

**Comment by dan-zeman** [comment]
This is a conversion of the original SynTagRus annotation to Universal Dependencies. It is expected that the dependency structure is different because the UD annotation guidelines are different from those of SynTagRus. In particular, multi-word personal names are connected using the relation [flat](http://universaldependencies.org/u/dep/flat.html), and the rule for this relation is that the first word (here _Абу_) is always the head and the subsequent words are attached to it.
